# 项目相关配置
ht:
  # 名称
  name: plateSaver
  # 版本
  version: 3.8.5
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ht/uploadPath，Linux配置 /home/ht/uploadPath）
#  profile: D:/ht/uploadPath
  profile: /home/ht/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ht: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 192.241.138.220
    # 端口，默认为6379
    port: 16399
    # 数据库索引
    database: 0
    # 密码
    password: 2157295634597a86894272aee59Fc082
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    username: plate_saver

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: amxyeowqiprtuvsbjnckzdghfl
    # 令牌有效期（默认30分钟）
    expireTime: 6000
  
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ht.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
mybatis-plus:
  type-aliases-package: com.ht.**.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql 

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 支付配置
pay:
  alipay:
    APP_ID: 2021000126204
    APP_PRIVATE_KEY: MVEuX+Pg1coO=
    ALIPAY_PUBLIC_KEY: MVa/4WCHD+OIFfIhP/uT66b4t4ywIDAQAB
    GATEWAY_HOST: opdev.com
    NOTIFY_URL: "http:/aliPayNotice"
    QUIT_URL: "http:y-response/pay-response?payNo="
    RETURN_URL: "http:-response/pay-response"
  wxpay:
    APP_ID: 'wxc02f2'
    OPEN_WECHAT: "wxe6c17"
    MINI_APP_ID: "wxd7f92"
    WEB_APP_ID: "wx33b9"
    MCH_ID: '17321'
    NOTIFY_URL: 'http://:30010/pay/api/wxPayNotice'
    # PRIVATE_KEY_PATH: "/home/ht/cert.pem"
    PRIVATE_KEY_PATH: "D:\\certs\\cert.pem"
    MERCHANT_SERIAL_NUMBER: "2DD729505C"
    API_V3_KEY: "cu"

ali:
  accessKeyId: LTnQHAV
  accessKeySecret: 5LngX
  safeContent:
    accessKeyId: "LTAI55wYpX"
    secret: "h2Ppusex"
  oss:
     endPoint: ossyuncs.com
     bucket: t
     pkgurl: https://n
  sms:
    signName: 戎
    template: S64